version: '3.1'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "3000:80"
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./app/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
