# 建置階段
FROM node:18 AS build
WORKDIR /app
COPY ./app/package*.json ./
RUN npm install
COPY ./app .
CMD ["npm", "run", "dev"]


# 部署階段
FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
